// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCARj4XcXqgJNE80fMlMR9D5krIekHKhnM',
    appId: '1:733768447663:web:19361a5bbc536739a8865a',
    messagingSenderId: '733768447663',
    projectId: 'spikers-13db7',
    authDomain: 'spikers-13db7.firebaseapp.com',
    storageBucket: 'spikers-13db7.firebasestorage.app',
    measurementId: 'G-EDY0G3KYHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxt7HrLeRTelIUrksZiRgXvUXkjNoc7tU',
    appId: '1:733768447663:android:73d7e630e7149102a8865a',
    messagingSenderId: '733768447663',
    projectId: 'spikers-13db7',
    storageBucket: 'spikers-13db7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeq04uG2Ap90ZcbhzS0mVeFBucI-azwxw',
    appId: '1:733768447663:ios:2d09e306634a9fe5a8865a',
    messagingSenderId: '733768447663',
    projectId: 'spikers-13db7',
    storageBucket: 'spikers-13db7.firebasestorage.app',
    iosClientId: '733768447663-peouo2oumovjbpb1f7g4j7nado2nkkt8.apps.googleusercontent.com',
    iosBundleId: 'com.jerusalem.spikers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeq04uG2Ap90ZcbhzS0mVeFBucI-azwxw',
    appId: '1:733768447663:ios:2d09e306634a9fe5a8865a',
    messagingSenderId: '733768447663',
    projectId: 'spikers-13db7',
    storageBucket: 'spikers-13db7.firebasestorage.app',
    iosClientId: '733768447663-peouo2oumovjbpb1f7g4j7nado2nkkt8.apps.googleusercontent.com',
    iosBundleId: 'com.jerusalem.spikers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCARj4XcXqgJNE80fMlMR9D5krIekHKhnM',
    appId: '1:733768447663:web:2ecd26bc0f2899aca8865a',
    messagingSenderId: '733768447663',
    projectId: 'spikers-13db7',
    authDomain: 'spikers-13db7.firebaseapp.com',
    storageBucket: 'spikers-13db7.firebasestorage.app',
    measurementId: 'G-1YJN73Z3SY',
  );
}
